### PR TITLE
add consistent OWNER env variable

### PR DESCRIPTION
**Pull request by johnseekins-pathccm**
Idea I had: If a user has many repos in a org, being able to skip writing `for :org/:repo` on every command would be nice. I _think_ this works, although I'm still testing a bit.

### CODE REVIEW

**Comment by stephenyeargin** [comment]
Haven't figured out why the CI scripts don't run on PRs (probably missing a trigger), but the branch has a few failed tests.

<details>
<summary>Test Output</summary>

```
> hubot-github-deployments@1.2.14 test
> mocha --require coffee-script/register "test/**/*.coffee" --reporter spec



  hubot-github-deployments
    ✔ responds with the list of recent deployments (1003ms)
    ✔ responds with the list of recent deployments for a specific repo (1000ms)
    ✔ gets the status of a single deployment (1001ms)
    ✔ gets the status of a single deployment for a specific repo (1001ms)
[Thu Sep 28 2023 20:23:53 GMT-0500 (Central Daylight Time)] ERROR ReferenceError: match is not defined
    at TextListener.callback (/Users/stephen/Sites/hubot-github-deployments/src/github-deployments.coffee:117:37)
    at executeListener (/Users/stephen/Sites/hubot-github-deployments/node_modules/hubot/src/listener.js:79:16)
    at allDone (/Users/stephen/Sites/hubot-github-deployments/node_modules/hubot/src/middleware.js:56:7)
    at /Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:254:13
    at Object.async.eachSeries (/Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:130:20)
    at async.reduce (/Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:248:15)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

    1) creates a deployment
[Thu Sep 28 2023 20:23:54 GMT-0500 (Central Daylight Time)] ERROR ReferenceError: match is not defined
    at TextListener.callback (/Users/stephen/Sites/hubot-github-deployments/src/github-deployments.coffee:117:37)
    at executeListener (/Users/stephen/Sites/hubot-github-deployments/node_modules/hubot/src/listener.js:79:16)
    at allDone (/Users/stephen/Sites/hubot-github-deployments/node_modules/hubot/src/middleware.js:56:7)
    at /Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:254:13
    at Object.async.eachSeries (/Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:130:20)
    at async.reduce (/Users/stephen/Sites/hubot-github-deployments/node_modules/async/lib/async.js:248:15)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

    2) creates a deployment for a specific repo
    ✔ lists the target environments (1001ms)
    ✔ lists all branches (1001ms)
    ✔ lists all branches for a specific repo (1001ms)
    ✔ lists branches matching search (1001ms)
    ✔ lists branches matching search for a specific repo (1002ms)
    ✔ lists branches matching search, no results (1002ms)
    ✔ lists branches matching search for a specific repo, no results (999ms)


  11 passing (13s)
  2 failing

  1) hubot-github-deployments
       creates a deployment:

      AssertionError: expected [ [ 'alice', …(1) ] ] to deeply equal [ Array(2) ]
      + expected - actual

         [
           "alice"
           "@hubot deploy master to production"
         ]
      +  [
      +    "hubot"
      +    "stephenyeargin deployed master to production"
      +  ]
       ]
      
      at Timeout._onTimeout (test/github-deployments_test.coffee:114:38)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
  

  2) hubot-github-deployments
       creates a deployment for a specific repo:

      AssertionError: expected [ [ 'alice', …(1) ] ] to deeply equal [ Array(2) ]
      + expected - actual

         [
           "alice"
           "@hubot deploy master to production for someone/somewhere"
         ]
      +  [
      +    "hubot"
      +    "stephenyeargin deployed master to production"
      +  ]
       ]
      
      at Timeout._onTimeout (test/github-deployments_test.coffee:133:38)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
  
```

</details>

**Comment by johnseekins-pathccm** [comment]
@stephenyeargin This _should_ work now. I believe you have to give me permissions to run jobs in branches on this repo. Also, I don't have a fully functioning install of this (missing a Github token...we're trying to decide the best way to generate it...) so while I _think_ it works right (and the tests pass), I'm a little hesitant to say "Yes! It works perfectly!"

**Review by stephenyeargin — APPROVED** [review]
I'm good with this. I personally hadn't used this integration in a while (moved on from the job that did) and spotted a handful of other quality of life changes that could be made.

**Comment by johnseekins-pathccm** [comment]
Any chance we could cut a release with these changes added?

**Comment by stephenyeargin** [comment]
Released in [v1.3.0](https://github.com/stephenyeargin/hubot-github-deployments/releases/tag/v1.3.0)

**Pull request merged**
